# -*- coding: utf-8 -*-
"""Cross-window falsification and optimization probes for S414."""

import argparse

from sim_strategy_backtest import backtest, parse_bkk, prepare_rates


WINDOWS = {
    "recent": (2, "2026-07-20T00:00:00+07:00"),
    "h1": (6, "2026-07-01T00:00:00+07:00"),
    "wf": (6, "2026-01-01T00:00:00+07:00"),
    "latest": (2, "2026-07-30T00:00:00+07:00"),
}
GROUPS = {
    "structure": (
        ("base", {}),
        ("fade", {"FADE_FLOW": True}),
        ("ratio100", {"IMPACT_RATIO_MIN": 1.00, "IMPACT_RISE_MIN": 0.00}),
        ("ratio125", {"IMPACT_RATIO_MIN": 1.25, "IMPACT_RISE_MIN": 0.15}),
        ("imbalance000", {"FLOW_IMBALANCE_MIN": 0.00}),
        ("imbalance015", {"FLOW_IMBALANCE_MIN": 0.15}),
        ("path006", {"PATH_EFFICIENCY_MIN": 0.06}),
        ("path020", {"PATH_EFFICIENCY_MIN": 0.20}),
        ("unaligned", {"REQUIRE_PATH_ALIGNMENT": False}),
        ("recent020", {"BASELINE_BARS": 60, "RECENT_BARS": 20}),
        ("recent028", {"BASELINE_BARS": 84, "RECENT_BARS": 28}),
        ("session0024", {"SESSION_START_HOUR": 0, "SESSION_END_HOUR": 24}),
        ("session0007", {"SESSION_START_HOUR": 0, "SESSION_END_HOUR": 7}),
        ("session1523", {"SESSION_START_HOUR": 15, "SESSION_END_HOUR": 23}),
        ("buy_only", {"ALLOW_SELL": False}),
        ("sell_only", {"ALLOW_BUY": False}),
    ),
    "finalists": (
        ("base", {}),
        ("ratio100", {"IMPACT_RATIO_MIN": 1.00, "IMPACT_RISE_MIN": 0.00}),
        ("ratio125", {"IMPACT_RATIO_MIN": 1.25, "IMPACT_RISE_MIN": 0.15}),
        ("imbalance000", {"FLOW_IMBALANCE_MIN": 0.00}),
        ("recent020", {"BASELINE_BARS": 60, "RECENT_BARS": 20}),
        ("recent020_imb000", {"BASELINE_BARS": 60, "RECENT_BARS": 20,
                              "FLOW_IMBALANCE_MIN": 0.00}),
        ("session0024", {"SESSION_START_HOUR": 0, "SESSION_END_HOUR": 24}),
        ("session0024_imb000", {"SESSION_START_HOUR": 0,
                                "SESSION_END_HOUR": 24,
                                "FLOW_IMBALANCE_MIN": 0.00}),
        ("session1523", {"SESSION_START_HOUR": 15, "SESSION_END_HOUR": 23}),
        ("session1523_imb000", {"SESSION_START_HOUR": 15,
                                "SESSION_END_HOUR": 23,
                                "FLOW_IMBALANCE_MIN": 0.00}),
        ("session1523_buy", {"SESSION_START_HOUR": 15,
                             "SESSION_END_HOUR": 23,
                             "ALLOW_SELL": False}),
        ("session1523_sell", {"SESSION_START_HOUR": 15,
                              "SESSION_END_HOUR": 23,
                              "ALLOW_BUY": False}),
    ),
    "salvage": (
        ("base", {}),
        ("fade", {"FADE_FLOW": True}),
        ("fade_buy", {"FADE_FLOW": True, "ALLOW_SELL": False}),
        ("fade_sell", {"FADE_FLOW": True, "ALLOW_BUY": False}),
        ("buy_only", {"ALLOW_SELL": False}),
        ("sell_only", {"ALLOW_BUY": False}),
        ("tp8", {"TP_RR": 8.0}),
        ("tp9", {"TP_RR": 9.0}),
        ("be050", {"BE_RR": 0.50}),
        ("be100", {"BE_RR": 1.00}),
        ("tp8_be050", {"TP_RR": 8.0, "BE_RR": 0.50}),
        ("session1523_tp8", {"SESSION_START_HOUR": 15,
                             "SESSION_END_HOUR": 23, "TP_RR": 8.0}),
        ("recent020_tp8", {"BASELINE_BARS": 60, "RECENT_BARS": 20,
                           "TP_RR": 8.0}),
    ),
    "fade_buy_opt": (
        ("fb_base", {"FADE_FLOW": True, "ALLOW_SELL": False}),
        ("fb_ratio100", {"FADE_FLOW": True, "ALLOW_SELL": False,
                         "IMPACT_RATIO_MIN": 1.00, "IMPACT_RISE_MIN": 0.00}),
        ("fb_ratio110", {"FADE_FLOW": True, "ALLOW_SELL": False,
                         "IMPACT_RATIO_MIN": 1.10}),
        ("fb_ratio125", {"FADE_FLOW": True, "ALLOW_SELL": False,
                         "IMPACT_RATIO_MIN": 1.25, "IMPACT_RISE_MIN": 0.15}),
        ("fb_imb000", {"FADE_FLOW": True, "ALLOW_SELL": False,
                       "FLOW_IMBALANCE_MIN": 0.00}),
        ("fb_imb015", {"FADE_FLOW": True, "ALLOW_SELL": False,
                       "FLOW_IMBALANCE_MIN": 0.15}),
        ("fb_path006", {"FADE_FLOW": True, "ALLOW_SELL": False,
                        "PATH_EFFICIENCY_MIN": 0.06}),
        ("fb_path018", {"FADE_FLOW": True, "ALLOW_SELL": False,
                        "PATH_EFFICIENCY_MIN": 0.18}),
        ("fb_path024", {"FADE_FLOW": True, "ALLOW_SELL": False,
                        "PATH_EFFICIENCY_MIN": 0.24}),
        ("fb_recent020", {"FADE_FLOW": True, "ALLOW_SELL": False,
                          "BASELINE_BARS": 60, "RECENT_BARS": 20}),
        ("fb_recent028", {"FADE_FLOW": True, "ALLOW_SELL": False,
                          "BASELINE_BARS": 84, "RECENT_BARS": 28}),
        ("fb_full", {"FADE_FLOW": True, "ALLOW_SELL": False,
                     "SESSION_START_HOUR": 0, "SESSION_END_HOUR": 24}),
        ("fb_asian", {"FADE_FLOW": True, "ALLOW_SELL": False,
                      "SESSION_START_HOUR": 0, "SESSION_END_HOUR": 7}),
        ("fb_us", {"FADE_FLOW": True, "ALLOW_SELL": False,
                   "SESSION_START_HOUR": 15, "SESSION_END_HOUR": 23}),
        ("fb_net020", {"FADE_FLOW": True, "ALLOW_SELL": False,
                       "NET_MOVE_ATR_MIN": 0.20}),
        ("fb_net050", {"FADE_FLOW": True, "ALLOW_SELL": False,
                       "NET_MOVE_ATR_MIN": 0.50}),
        ("fb_volume080", {"FADE_FLOW": True, "ALLOW_SELL": False,
                          "EVENT_VOLUME_RATIO_MIN": 0.80}),
        ("fb_volume120", {"FADE_FLOW": True, "ALLOW_SELL": False,
                          "EVENT_VOLUME_RATIO_MIN": 1.20}),
        ("fb_body035", {"FADE_FLOW": True, "ALLOW_SELL": False,
                        "EVENT_BODY_ATR_MIN": 0.35}),
        ("fb_body055", {"FADE_FLOW": True, "ALLOW_SELL": False,
                        "EVENT_BODY_ATR_MIN": 0.55}),
        ("fb_close065", {"FADE_FLOW": True, "ALLOW_SELL": False,
                         "EVENT_CLOSE_FRACTION": 0.65}),
        ("fb_close075", {"FADE_FLOW": True, "ALLOW_SELL": False,
                         "EVENT_CLOSE_FRACTION": 0.75}),
        ("fb_tp8", {"FADE_FLOW": True, "ALLOW_SELL": False,
                    "TP_RR": 8.0}),
        ("fb_tp9", {"FADE_FLOW": True, "ALLOW_SELL": False,
                    "TP_RR": 9.0}),
    ),
    "fade_buy_combo": (
        ("body050", {"FADE_FLOW": True, "ALLOW_SELL": False,
                     "EVENT_BODY_ATR_MIN": 0.50}),
        ("body055", {"FADE_FLOW": True, "ALLOW_SELL": False,
                     "EVENT_BODY_ATR_MIN": 0.55}),
        ("body060", {"FADE_FLOW": True, "ALLOW_SELL": False,
                     "EVENT_BODY_ATR_MIN": 0.60}),
        ("body065", {"FADE_FLOW": True, "ALLOW_SELL": False,
                     "EVENT_BODY_ATR_MIN": 0.65}),
        ("tp750", {"FADE_FLOW": True, "ALLOW_SELL": False,
                   "TP_RR": 7.50}),
        ("tp800", {"FADE_FLOW": True, "ALLOW_SELL": False,
                   "TP_RR": 8.00}),
        ("tp825", {"FADE_FLOW": True, "ALLOW_SELL": False,
                   "TP_RR": 8.25}),
        ("body055_tp750", {"FADE_FLOW": True, "ALLOW_SELL": False,
                           "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 7.50}),
        ("body055_tp800", {"FADE_FLOW": True, "ALLOW_SELL": False,
                           "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 8.00}),
        ("body055_tp825", {"FADE_FLOW": True, "ALLOW_SELL": False,
                           "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 8.25}),
        ("body055_imb015", {"FADE_FLOW": True, "ALLOW_SELL": False,
                            "EVENT_BODY_ATR_MIN": 0.55,
                            "FLOW_IMBALANCE_MIN": 0.15}),
        ("body055_ratio110", {"FADE_FLOW": True, "ALLOW_SELL": False,
                              "EVENT_BODY_ATR_MIN": 0.55,
                              "IMPACT_RATIO_MIN": 1.10}),
        ("body055_volume120", {"FADE_FLOW": True, "ALLOW_SELL": False,
                               "EVENT_BODY_ATR_MIN": 0.55,
                               "EVENT_VOLUME_RATIO_MIN": 1.20}),
        ("body055_path024", {"FADE_FLOW": True, "ALLOW_SELL": False,
                             "EVENT_BODY_ATR_MIN": 0.55,
                             "PATH_EFFICIENCY_MIN": 0.24}),
        ("body055_tp800_imb015", {
            "FADE_FLOW": True, "ALLOW_SELL": False,
            "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 8.00,
            "FLOW_IMBALANCE_MIN": 0.15,
        }),
    ),
    "final_tune": (
        ("b055_t800_i010", {"FADE_FLOW": True, "ALLOW_SELL": False,
                            "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 8.00,
                            "FLOW_IMBALANCE_MIN": 0.10}),
        ("b055_t800_i012", {"FADE_FLOW": True, "ALLOW_SELL": False,
                            "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 8.00,
                            "FLOW_IMBALANCE_MIN": 0.12}),
        ("b055_t800_i015", {"FADE_FLOW": True, "ALLOW_SELL": False,
                            "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 8.00,
                            "FLOW_IMBALANCE_MIN": 0.15}),
        ("b055_t800_i018", {"FADE_FLOW": True, "ALLOW_SELL": False,
                            "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 8.00,
                            "FLOW_IMBALANCE_MIN": 0.18}),
        ("b055_t800_i020", {"FADE_FLOW": True, "ALLOW_SELL": False,
                            "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 8.00,
                            "FLOW_IMBALANCE_MIN": 0.20}),
        ("b050_t800_i015", {"FADE_FLOW": True, "ALLOW_SELL": False,
                            "EVENT_BODY_ATR_MIN": 0.50, "TP_RR": 8.00,
                            "FLOW_IMBALANCE_MIN": 0.15}),
        ("b060_t800_i015", {"FADE_FLOW": True, "ALLOW_SELL": False,
                            "EVENT_BODY_ATR_MIN": 0.60, "TP_RR": 8.00,
                            "FLOW_IMBALANCE_MIN": 0.15}),
        ("b065_t800_i015", {"FADE_FLOW": True, "ALLOW_SELL": False,
                            "EVENT_BODY_ATR_MIN": 0.65, "TP_RR": 8.00,
                            "FLOW_IMBALANCE_MIN": 0.15}),
        ("b055_t750_i015", {"FADE_FLOW": True, "ALLOW_SELL": False,
                            "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 7.50,
                            "FLOW_IMBALANCE_MIN": 0.15}),
        ("b055_t775_i015", {"FADE_FLOW": True, "ALLOW_SELL": False,
                            "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 7.75,
                            "FLOW_IMBALANCE_MIN": 0.15}),
        ("b055_t800_i015_v110", {
            "FADE_FLOW": True, "ALLOW_SELL": False,
            "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 8.00,
            "FLOW_IMBALANCE_MIN": 0.15, "EVENT_VOLUME_RATIO_MIN": 1.10,
        }),
        ("b055_t800_i015_p018", {
            "FADE_FLOW": True, "ALLOW_SELL": False,
            "EVENT_BODY_ATR_MIN": 0.55, "TP_RR": 8.00,
            "FLOW_IMBALANCE_MIN": 0.15, "PATH_EFFICIENCY_MIN": 0.18,
        }),
    ),
    "body_cliff": (
        ("body065", {"FADE_FLOW": True, "ALLOW_SELL": False,
                     "EVENT_BODY_ATR_MIN": 0.65, "TP_RR": 8.00,
                     "FLOW_IMBALANCE_MIN": 0.15}),
        ("body070", {"FADE_FLOW": True, "ALLOW_SELL": False,
                     "EVENT_BODY_ATR_MIN": 0.70, "TP_RR": 8.00,
                     "FLOW_IMBALANCE_MIN": 0.15}),
        ("body075", {"FADE_FLOW": True, "ALLOW_SELL": False,
                     "EVENT_BODY_ATR_MIN": 0.75, "TP_RR": 8.00,
                     "FLOW_IMBALANCE_MIN": 0.15}),
        ("body080", {"FADE_FLOW": True, "ALLOW_SELL": False,
                     "EVENT_BODY_ATR_MIN": 0.80, "TP_RR": 8.00,
                     "FLOW_IMBALANCE_MIN": 0.15}),
        ("body090", {"FADE_FLOW": True, "ALLOW_SELL": False,
                     "EVENT_BODY_ATR_MIN": 0.90, "TP_RR": 8.00,
                     "FLOW_IMBALANCE_MIN": 0.15}),
    ),
}


def _view(summary):
    return {key: summary[key] for key in (
        "closed", "wins", "win_rate", "net_profit", "pnl_per_day",
        "pnl_per_month", "profit_factor", "max_drawdown",
    )}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--window", choices=tuple(WINDOWS), required=True)
    parser.add_argument("--group", choices=tuple(GROUPS), required=True)
    args = parser.parse_args()
    months, end_text = WINDOWS[args.window]
    end = parse_bkk(end_text)
    prepared = prepare_rates(months, "M5", end, 300)
    for name, cfg in GROUPS[args.group]:
        summary, _ = backtest(
            414, months, "M5", 0.20, 0.01, end, 300, cfg, prepared
        )
        print(name, _view(summary), flush=True)


if __name__ == "__main__":
    main()
