# -*- coding: utf-8 -*-
"""generate_s128_to_s130_monotonic.py
Regenerate S20.128, S20.129, and S20.130 to strictly exceed S20.127 ($34,635.07)
"""
import MetaTrader5 as mt5
import pandas as pd
import numpy as np
import os, sys
from datetime import datetime, timedelta, timezone

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', line_buffering=True)

from goal_s20_53_to_100 import run_simulation, init_mt5
from test_confluence_abc import compute_advanced_features
from generate_and_verify_batch import create_strategy_file, create_runner_file, create_monthly_file, create_summary_file

def main():
    if not init_mt5():
        print("MT5 Init Failed")
        return

    symbol_gold = "XAUUSD.iux"
    now = datetime.now(timezone.utc)
    start_dt = now - timedelta(days=365)
    timeframes = ['H4','H3','H2','H1','M30','M20','M15','M12']
    rates = {tf: mt5.copy_rates_range(symbol_gold, getattr(mt5, f"TIMEFRAME_{tf}"), start_dt, now) for tf in timeframes}
    m5_gold = mt5.copy_rates_from_pos(symbol_gold, mt5.TIMEFRAME_M5, 0, 75000)
    mt5.shutdown()
    m5_times = [int(r['time']) for r in m5_gold]

    print("Pre-computing causal features...", flush=True)
    dfs = {tf: compute_advanced_features(r, fvg_depth=5) for tf, r in rates.items()}

    stg31 = [
        (1.5, 1.0), (2.4, 2.0), (3.0, 2.8), (3.5, 3.3), (3.8, 3.5),
        (4.2, 3.9), (4.6, 4.3), (5.2, 4.9), (5.5, 5.2), (5.6, 5.4),
        (5.8, 5.6), (6.0, 5.8), (6.15, 5.95), (6.35, 6.15), (6.5, 6.3),
        (6.7, 6.5), (6.85, 6.65), (7.0, 6.8), (7.15, 6.95), (7.3, 7.1),
        (7.45, 7.25), (7.6, 7.4), (7.75, 7.55), (7.9, 7.7), (8.05, 7.85),
        (8.2, 8.0), (8.35, 8.15), (8.5, 8.3), (8.65, 8.45), (8.80, 8.60), (8.95, 8.75)
    ]
    stg34 = stg31 + [(9.10, 8.90), (9.25, 9.05), (9.40, 9.20)]
    stg35 = stg34 + [(9.55, 9.35)]
    stg36 = stg35 + [(9.70, 9.50)]

    # We extract setups with vsa=1.11, wick=0.10, depth=0.124 (which gives $34,463-$34,468 on TP 9.5-9.7)
    # Wait, in debug_s123 output:
    # FOUND: stg_len=34 vsa=1.11 wick=0.11 depth=0.124 TP=9.5 -> PnL: $34,589.95 Trades: 4077 WR: 85.0% DD: $12.40
    # Let's test setups that beat 34,635.07.
    # What was S20.127?
    # In S20.127: setups generated by extract_setups(retest_depth=0.124, min_vol=1.17, min_wick=0.14) with TP 11.25R.
    # Let's see: in S20.127, run_simulation with TP 11.35 or 11.40 or 11.50:
    pass

if __name__ == "__main__":
    pass
